name: LobbyProxyCore
main: Asada\lobbyproxycore\Main
version: 1.0.0
api: 3.16.0

author: Asada
description: Plugin for use many features in WaterdogProxy with API StarGate-Atlantis
website: ini.space\Asada

commands:
    store:
        description: Open Store
permissions:
    lobbycore.transfer.reason:
        default: op
    lobbycore.whitelist.bypass:
        default: op
    lobbycore.join.owner:
        default: op
    lobbycore.join.staff:
        default: op